# Generated by Django 5.0 on 2026-04-04 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0002_alerte_annee_min_alerte_boite_vitesse_and_more'),
        ('annonces', '0004_battle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_rapport', models.CharField(choices=[('complet', 'Rapport Complet'), ('comparatif', 'Analyse Comparative'), ('historique', 'Historique Prix'), ('estimation', "Rapport d'Estimation")], max_length=20)),
                ('template_html', models.TextField()),
                ('styles_css', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_par_defaut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de rapport',
                'verbose_name_plural': 'Templates de rapports',
            },
        ),
        migrations.CreateModel(
            name='RapportPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(choices=[('complet', 'Rapport Complet'), ('comparatif', 'Analyse Comparative'), ('historique', 'Historique Prix'), ('estimation', "Rapport d'Estimation")], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('contenu_json', models.JSONField(blank=True, default=dict)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/pdf/')),
                ('prix', models.DecimalField(decimal_places=2, default=9.99, max_digits=6)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('generation', 'En cours de génération'), ('termine', 'Terminé'), ('erreur', 'Erreur'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genere_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('alerte_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertes.alerte')),
                ('annonce_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_principaux', to='annonces.annonce')),
                ('annonces_comparees', models.ManyToManyField(blank=True, related_name='rapports_comparatifs', to='annonces.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport PDF',
                'verbose_name_plural': 'Rapports PDF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('temps_execution', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='rapports.rapportpdf')),
            ],
            options={
                'verbose_name': 'Historique de génération',
                'verbose_name_plural': 'Historiques de génération',
                'ordering': ['-created_at'],
            },
        ),
    ]
