# Generated by Django 4.2.29 on 2026-04-11 13:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0005_statistiqueannonce_comparaisonannonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiee'), ('reserved', 'Reservee'), ('sold', 'Vendue'), ('cancelled', 'Annulee')], default='draft', max_length=20)),
                ('logistics_mode', models.CharField(choices=[('platform', 'Logistique marketplace'), ('seller', 'Expedition vendeur'), ('pickup', 'Retrait sur place')], default='platform', max_length=20)),
                ('secure_payment_required', models.BooleanField(default=True)),
                ('escrow_required', models.BooleanField(default=True)),
                ('logistics_enabled', models.BooleanField(default=True)),
                ('marketplace_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('escrow_window_days', models.PositiveSmallIntegerField(default=7)),
                ('verification_snapshot', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='annonces.annonce')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiee'), ('payment_pending', 'Paiement en attente'), ('escrow_funded', 'Escrow alimente'), ('processing', 'Preparation'), ('in_transit', 'En transit'), ('delivered', 'Livree'), ('completed', 'Completee'), ('disputed', 'En litige'), ('cancelled', 'Annulee'), ('refunded', 'Remboursee')], default='initiated', max_length=30)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marketplace_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logistics_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('secure_payment_required', models.BooleanField(default=True)),
                ('escrow_required', models.BooleanField(default=True)),
                ('logistics_required', models.BooleanField(default=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('buyer_note', models.TextField(blank=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.marketplacelisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('approved', 'Approuvee'), ('rejected', 'Rejetee')], default='draft', max_length=20)),
                ('legal_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(default='DZ', max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('national_id', 'Carte nationale'), ('passport', 'Passeport'), ('driver_license', 'Permis de conduire'), ('business_registration', 'Registre commercial')], max_length=30)),
                ('document_number_last4', models.CharField(max_length=4)),
                ('document_front_url', models.URLField(blank=True)),
                ('document_back_url', models.URLField(blank=True)),
                ('selfie_url', models.URLField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('review_notes', models.TextField(blank=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('mock', 'Mock'), ('manual', 'Manuel')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Cree'), ('requires_action', 'Action requise'), ('processing', 'Traitement'), ('succeeded', 'Reussi'), ('failed', 'Echoue'), ('refunded', 'Rembourse')], default='created', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.marketplaceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_events', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.marketplacelisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.marketplaceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('shipped', 'Expédié'), ('picked_up', 'Recupere'), ('in_transit', 'En transit'), ('delivered', 'Livre'), ('failed', 'Echec'), ('cancelled', 'Annule')], default='pending', max_length=20)),
                ('provider', models.CharField(default='AutoIntel Logistics', max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='marketplace.marketplaceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('funded', 'Alimente'), ('released', 'Libere'), ('refunded', 'Rembourse'), ('disputed', 'En litige')], default='pending', max_length=20)),
                ('held_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_token_hash', models.CharField(max_length=128)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='marketplace.marketplaceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
