# Generated by Django 4.2.29 on 2026-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsshipment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Planifie'), ('picked_up', 'Recupere'), ('in_transit', 'En transit'), ('delivered', 'Livre'), ('failed', 'Echec'), ('cancelled', 'Annule')], default='pending', max_length=20),
        ),
    ]
