# Generated by Django 5.0 on 2026-04-04 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0002_alerte_annee_min_alerte_boite_vitesse_and_more'),
        ('annonces', '0004_battle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('valeur', models.CharField(help_text='Email, Chat ID Telegram ou numéro WhatsApp', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Le canal a été vérifié')),
                ('is_active', models.BooleanField(default=True, help_text='Le canal est actif pour les notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaux_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('erreur_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alertes.alerte')),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='notifications.canalnotification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
