# Generated by Django 4.2.30 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='is_lu',
            field=models.BooleanField(default=False),
        ),
    ]
