# Generated by Django 4.2.29 on 2026-04-11 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicules', '0001_initial'),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.IntegerField(default=0)),
                ('score_prix', models.IntegerField(default=0)),
                ('score_besoins', models.IntegerField(default=0)),
                ('score_marche', models.IntegerField(default=0)),
                ('score_disponibilite', models.IntegerField(default=0)),
                ('raisons_recommandation', models.JSONField(blank=True, default=list)),
                ('points_forts', models.JSONField(blank=True, default=list)),
                ('points_faibles', models.JSONField(blank=True, default=list)),
                ('prix_estime_1an', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_estime_3ans', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confiance_prediction', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'Recommandation véhicule',
                'verbose_name_plural': 'Recommandations véhicules',
                'ordering': ['-score_total', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('types_vehicule', models.JSONField(blank=True, default=list)),
                ('usage_principal', models.CharField(choices=[('quotidien', 'Usage quotidien'), ('professionnel', 'Usage professionnel'), ('loisir', 'Loisir'), ('famille', 'Familial'), ('sportif', 'Sportif')], default='quotidien', max_length=100)),
                ('kilometrage_annuel', models.IntegerField(default=15000)),
                ('preferences_carburant', models.JSONField(blank=True, default=list)),
                ('places_minimales', models.IntegerField(default=4)),
                ('porte_minimales', models.IntegerField(default=3)),
                ('transmission_preferree', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique'), ('les_deux', 'Les deux')], default='les_deux', max_length=20)),
                ('score_ecologique', models.IntegerField(default=50)),
                ('score_budget', models.IntegerField(default=50)),
                ('score_praticite', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marques_preferrees', models.ManyToManyField(blank=True, to='vehicules.marque')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ia_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse profil IA',
                'verbose_name_plural': 'Analyses profils IA',
            },
        ),
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_insight', models.CharField(choices=[('tendance_prix', 'Tendance des prix'), ('opportunite', 'Opportunité'), ('alerte_marche', 'Alerte marché'), ('conseil_achat', 'Conseil achat'), ('conseil_vente', 'Conseil vente'), ('prediction', 'Prédiction')], max_length=50)),
                ('categories_vehicules', models.JSONField(blank=True, default=list)),
                ('fourchettes_prix', models.JSONField(blank=True, default=dict)),
                ('niveau_impact', models.IntegerField(default=50)),
                ('confiance', models.IntegerField(default=70)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marques_concernees', models.ManyToManyField(blank=True, to='vehicules.marque')),
            ],
            options={
                'verbose_name': 'Aperçu marché',
                'verbose_name_plural': 'Aperçus marché',
                'ordering': ['-niveau_impact', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_donnee', models.CharField(choices=[('conversation', 'Conversation'), ('recommandation_feedback', 'Feedback recommandation'), ('prediction_resultat', 'Résultat prédiction'), ('comportement_recherche', 'Comportement recherche')], max_length=50)),
                ('donnees_entree', models.JSONField(default=dict)),
                ('donnees_sortie', models.JSONField(default=dict)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('feedback_utilisateur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donnée apprentissage',
                'verbose_name_plural': 'Données apprentissage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_principale', models.CharField(choices=[('recherche_vehicule', 'Recherche véhicule'), ('conseil_achat', 'Conseil achat'), ('estimation_prix', 'Estimation prix'), ('information_marche', 'Information marché'), ('comparaison', 'Comparaison'), ('avis_expert', 'Avis expert'), ('autre', 'Autre')], max_length=100)),
                ('entites', models.JSONField(blank=True, default=dict)),
                ('sentiment', models.CharField(choices=[('positif', 'Positif'), ('neutre', 'Neutre'), ('negatif', 'Négatif')], default='neutre', max_length=20)),
                ('niveau_urgence', models.IntegerField(default=50)),
                ('contexte_conversation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_analysis', to='ai_assistant.message')),
            ],
            options={
                'verbose_name': 'Analyse intention',
                'verbose_name_plural': 'Analyses intentions',
            },
        ),
    ]
