# Generated by Django 5.0 on 2026-03-21 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(max_length=20)),
                ('boite', models.CharField(blank=True, max_length=20)),
                ('puissance', models.IntegerField(blank=True, null=True)),
                ('pays', models.CharField(max_length=5)),
                ('prix_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fourchette_basse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fourchette_haute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiabilite', models.CharField(max_length=20)),
                ('nb_annonces_reference', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
