# Generated by Django 5.0 on 2026-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='annee_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='boite_vitesse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alerte',
            name='prix_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='push_actif',
            field=models.BooleanField(default=True),
        ),
    ]
