# Generated by Django 5.0 on 2026-03-21 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('legendaire', 'Légendaire')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('ac_reward', models.IntegerField(default=25)),
                ('cible_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('niveau', models.IntegerField(default=1)),
                ('autocoin_balance', models.IntegerField(default=100)),
                ('estimations_ce_mois', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('type', models.CharField(choices=[('gain_estimation', 'Estimation effectuée'), ('gain_bonne_affaire', 'Bonne affaire détectée'), ('gain_defi', 'Défi complété'), ('depense_shop', 'Achat boutique'), ('gain_battle', 'Battle gagnée')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.profiljoueur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefiJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.defi')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_en_cours', to='gamification.profiljoueur')),
            ],
            options={
                'unique_together': {('profil', 'defi')},
            },
        ),
    ]
