# Generated by Django 5.0 on 2026-04-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix_ac', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('gain_estimation', 'Estimation effectuée'), ('gain_bonne_affaire', 'Bonne affaire détectée'), ('gain_defi', 'Défi complété'), ('depense_boutique', 'Achat en boutique'), ('gain_battle', 'Battle gagnée')], max_length=50),
        ),
        migrations.CreateModel(
            name='AchatJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='gamification.profiljoueur')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.boutiqueitem')),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
    ]
