# Generated by Django 5.0 on 2026-03-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('categorie', models.CharField(default='berline', max_length=50)),
            ],
            options={
                'unique_together': {('marque', 'modele')},
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], default='essence', max_length=20)),
                ('boite', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20)),
                ('puissance', models.IntegerField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ecart_prix', models.FloatField(blank=True, null=True)),
                ('score_affaire', models.IntegerField(default=0)),
                ('est_bonne_affaire', models.BooleanField(default=False)),
                ('source', models.CharField(default='manuel', max_length=100)),
                ('url_originale', models.URLField(blank=True, null=True, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(choices=[('DZ', 'Algérie'), ('TN', 'Tunisie'), ('FR', 'France'), ('MA', 'Maroc')], default='DZ', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='annonces.vehicule')),
            ],
            options={
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['est_bonne_affaire'], name='annonces_an_est_bon_265f52_idx'), models.Index(fields=['pays'], name='annonces_an_pays_327764_idx'), models.Index(fields=['prix'], name='annonces_an_prix_81ede3_idx')],
            },
        ),
    ]
