# Generated by Django 5.0 on 2026-04-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_recherchesauvegardee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_v1', models.IntegerField(default=0)),
                ('votes_v2', models.IntegerField(default=0)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_creees', to=settings.AUTH_USER_MODEL)),
                ('vehicule_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_v1', to='annonces.annonce')),
                ('vehicule_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_v2', to='annonces.annonce')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
