# Generated by Django 4.2.29 on 2026-04-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0004_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vues_totales', models.IntegerField(default=0)),
                ('vues_uniques', models.IntegerField(default=0)),
                ('contacts_totales', models.IntegerField(default=0)),
                ('favoris_totales', models.IntegerField(default=0)),
                ('vues_jour', models.JSONField(default=dict)),
                ('contacts_jour', models.JSONField(default=dict)),
                ('favoris_jour', models.JSONField(default=dict)),
                ('pays_visiteurs', models.JSONField(default=dict)),
                ('sources_visiteurs', models.JSONField(default=dict)),
                ('dernier_calcul', models.DateTimeField(auto_now=True)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='annonces.annonce')),
            ],
            options={
                'ordering': ['-dernier_calcul'],
            },
        ),
        migrations.CreateModel(
            name='ComparaisonAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('criteres', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_publique', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('annonces', models.ManyToManyField(related_name='comparaisons', to='annonces.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AlerteRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('filtres', models.JSONField(default=dict)),
                ('frequence', models.CharField(choices=[('immediat', 'Immédiat'), ('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire')], default='quotidien', max_length=20)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_notification', models.DateTimeField(blank=True, null=True)),
                ('nombre_resultats', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_recherche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='VisiteAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('duree_visite', models.IntegerField(blank=True, null=True)),
                ('provient_de', models.CharField(blank=True, max_length=100)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='annonces.annonce')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_visite'],
                'indexes': [models.Index(fields=['annonce', 'date_visite'], name='annonces_vi_annonce_f224c9_idx'), models.Index(fields=['utilisateur', 'date_visite'], name='annonces_vi_utilisa_dbeffd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('prix_fictif', 'Prix fictif'), ('vehicule_volé', 'Véhicule volé'), ('arnaque', "Tentative d'arnaque"), ('infos_fausses', 'Informations fausses'), ('vehicule_existe_pas', "Véhicule n'existe pas"), ('double_annonce', 'Annonce en double'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('est_traite', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('note_traitement', models.TextField(blank=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces.annonce')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_signalement'],
                'unique_together': {('annonce', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='NotificationAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle_annonce', 'Nouvelle annonce correspondante'), ('prix_baisse', 'Baisse de prix'), ('bonne_affaire', 'Bonne affaire détectée'), ('annonces_similaires', 'Annonces similaires'), ('expiration_alerte', 'Alerte expiration')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('donnees_supplementaires', models.JSONField(default=dict)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'est_lue', 'date_creation'], name='annonces_no_utilisa_f424ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200)),
                ('filtres', models.JSONField(default=dict)),
                ('nombre_resultats', models.IntegerField(default=0)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_recherche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recherche'],
                'indexes': [models.Index(fields=['user', 'date_recherche'], name='annonces_hi_user_id_dd80ea_idx'), models.Index(fields=['terme'], name='annonces_hi_terme_ccaf44_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('aspects', models.JSONField(default=dict)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_evaluation'],
                'unique_together': {('vendeur', 'evaluateur', 'annonce')},
            },
        ),
        migrations.CreateModel(
            name='ContactVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
                ('est_repondu', models.BooleanField(default=False)),
                ('acheteur_potentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='annonces.annonce')),
            ],
            options={
                'ordering': ['-date_contact'],
                'unique_together': {('annonce', 'acheteur_potentiel')},
            },
        ),
    ]
