# Generated by Django 4.2.29 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_statistiqueannonce_comparaisonannonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('populaire', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
