# Generated by Django 4.2.29 on 2026-04-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_create_marque_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='marque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='annonces.marque'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='modele',
            field=models.CharField(db_index=True, default='Inconnu', max_length=100),
        ),
    ]
