# Generated by Django 4.2.29 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_add_marque_to_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
