# Generated by Django 4.2.29 on 2026-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_alter_annonce_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='alerterecherche',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='comparaisonannonce',
                    name='annonces',
                ),
                migrations.RemoveField(
                    model_name='comparaisonannonce',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='contactvendeur',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='contactvendeur',
                    name='acheteur_potentiel',
                ),
                migrations.RemoveField(
                    model_name='contactvendeur',
                    name='annonce',
                ),
                migrations.AlterUniqueTogether(
                    name='evaluationvendeur',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='evaluationvendeur',
                    name='annonce',
                ),
                migrations.RemoveField(
                    model_name='evaluationvendeur',
                    name='evaluateur',
                ),
                migrations.RemoveField(
                    model_name='evaluationvendeur',
                    name='vendeur',
                ),
                migrations.RemoveField(
                    model_name='historiquerecherche',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='notificationannonce',
                    name='annonce',
                ),
                migrations.RemoveField(
                    model_name='notificationannonce',
                    name='utilisateur',
                ),
                migrations.AlterUniqueTogether(
                    name='signalement',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='signalement',
                    name='annonce',
                ),
                migrations.RemoveField(
                    model_name='signalement',
                    name='traite_par',
                ),
                migrations.RemoveField(
                    model_name='signalement',
                    name='utilisateur',
                ),
                migrations.RemoveField(
                    model_name='statistiqueannonce',
                    name='annonce',
                ),
                migrations.AlterUniqueTogether(
                    name='vehicule',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='visiteannonce',
                    name='annonce',
                ),
                migrations.RemoveField(
                    model_name='visiteannonce',
                    name='utilisateur',
                ),
                migrations.AlterModelOptions(
                    name='battle',
                    options={},
                ),
                migrations.RemoveIndex(
                    model_name='annonce',
                    name='annonces_an_est_bon_265f52_idx',
                ),
                migrations.RemoveIndex(
                    model_name='annonce',
                    name='annonces_an_pays_327764_idx',
                ),
                migrations.RemoveIndex(
                    model_name='annonce',
                    name='annonces_an_prix_81ede3_idx',
                ),
                migrations.RemoveField(
                    model_name='annonce',
                    name='date_collecte',
                ),
                migrations.RemoveField(
                    model_name='annonce',
                    name='vehicule',
                ),
                migrations.AddField(
                    model_name='battle',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AddField(
                    model_name='recherchesauvegardee',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='annee',
                    field=models.SmallIntegerField(db_index=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='boite',
                    field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='carburant',
                    field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], db_index=True, max_length=20),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='date_publication',
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='est_active',
                    field=models.BooleanField(db_index=True, default=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='est_bonne_affaire',
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='pays',
                    field=models.CharField(choices=[('DZ', 'Algérie'), ('TN', 'Tunisie'), ('FR', 'France'), ('MA', 'Maroc')], db_index=True, default='DZ', max_length=5),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='prix',
                    field=models.DecimalField(decimal_places=2, max_digits=12),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='prix_estime',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='puissance',
                    field=models.SmallIntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='score_affaire',
                    field=models.SmallIntegerField(db_index=True, default=0),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='source',
                    field=models.CharField(default='scraping', max_length=50),
                ),
                migrations.AlterField(
                    model_name='annonce',
                    name='ville',
                    field=models.CharField(blank=True, default='Inconnue', max_length=100),
                ),
                migrations.AlterField(
                    model_name='battle',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='marque',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='recherchesauvegardee',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AddIndex(
                    model_name='annonce',
                    index=models.Index(fields=['pays', 'est_bonne_affaire'], name='annonces_an_pays_f074b0_idx'),
                ),
                migrations.AddIndex(
                    model_name='annonce',
                    index=models.Index(fields=['marque', 'modele', 'annee'], name='annonces_an_marque__00bd88_idx'),
                ),
                migrations.AddIndex(
                    model_name='annonce',
                    index=models.Index(fields=['prix', 'pays'], name='annonces_an_prix_d30ce6_idx'),
                ),
                migrations.AddIndex(
                    model_name='annonce',
                    index=models.Index(fields=['est_active', 'date_publication'], name='annonces_an_est_act_e30547_idx'),
                ),
                migrations.DeleteModel(
                    name='AlerteRecherche',
                ),
                migrations.DeleteModel(
                    name='ComparaisonAnnonce',
                ),
                migrations.DeleteModel(
                    name='ContactVendeur',
                ),
                migrations.DeleteModel(
                    name='EvaluationVendeur',
                ),
                migrations.DeleteModel(
                    name='HistoriqueRecherche',
                ),
                migrations.DeleteModel(
                    name='NotificationAnnonce',
                ),
                migrations.DeleteModel(
                    name='Signalement',
                ),
                migrations.DeleteModel(
                    name='StatistiqueAnnonce',
                ),
                migrations.DeleteModel(
                    name='Vehicule',
                ),
                migrations.DeleteModel(
                    name='VisiteAnnonce',
                ),
            ],
        ),
    ]
